# vim: set expandtab shiftwidth=4 softtabstop=4 :
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    example:
    kdc_primary:
    kdc_secondary:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_shell:
    tpmsocket_shell:
    tpm_alicia:
    tpmsocket_alicia:
    tpm_auth_certificate:
    tpmsocket_auth_certificate:
    tpm_auth_kerberos:
    tpmsocket_auth_kerberos:
    x1_kdc:
    x1_backdoor:

networks:
    hcpnetwork:
        # internal: true

services:
    common:
        image: hcp_caboodle:trixie
        init: true
        volumes:
          - ${TOP}/hcp:/hcp:ro
          - ./usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}
          - PYTHONPATH=/hcp/python
        healthcheck:
            test: /hcp/python/HcpToolHealthcheck.py
            timeout: 10s
            interval: 20s

    common_tpm:
        extends: common
        network_mode: "none"
        environment:
          - HCP_CONFIG_SCOPE=.tpm

    common_nontpm:
        extends: common
        networks:
          - hcpnetwork
        volumes:
          - ./_testcreds/capublic:/capublic:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollhealthclient:/enrollhealthclient:ro

    orchestrator:
        extends: common_nontpm
        hostname: orchestrator.hcphacking.xyz
        volumes:
          - ./_testcreds/enrollclient:/enrollclient:ro
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpm_shell:/tpm_shell
          - tpm_alicia:/tpm_alicia
          - tpm_auth_certificate:/tpm_auth_certificate
          - tpm_auth_kerberos:/tpm_auth_kerberos
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/orchestrator.json

    enrollsvc:
        extends: common_nontpm
        hostname: enrollsvc.hcphacking.xyz
        volumes:
          - example:/example
          - ./_testcreds/enrollsvc:/enrollsvc:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/enrollsvc.json

    attestsvc:
        extends: common_nontpm
        hostname: attestsvc.hcphacking.xyz
        volumes:
          - example:/example
          - ./_testcreds/attestsvc:/attestsvc:ro
          - ./_testcreds/attestnoncer:/attestnoncer:ro
          - ./_testcreds/enrollsigner:/enrollsigner:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/caprivate:/caprivate:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/attestsvc.json

    kdc_primary:
        extends: common_nontpm
        hostname: primary.kdc.hcphacking.xyz
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_primary_tpm:
        extends: common_tpm
        hostname: kdc_primary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_secondary:
        extends: common_nontpm
        hostname: secondary.kdc.hcphacking.xyz
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_secondary_tpm:
        extends: common_tpm
        hostname: kdc_secondary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    shell:
        extends: common_nontpm
        hostname: shell.hcphacking.xyz
        volumes:
          - tpmsocket_shell:/tpmsocket_shell
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/shell.json

    shell_tpm:
        extends: common_tpm
        hostname: shell_tpm.hcphacking.xyz
        volumes:
          - tpm_shell:/tpm_shell
          - tpmsocket_shell:/tpmsocket_shell
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/shell.json

    alicia:
        extends: common_nontpm
        hostname: alicia.hcphacking.xyz
        volumes:
          - tpmsocket_alicia:/tpmsocket_alicia
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/alicia.json

    alicia_tpm:
        extends: common_tpm
        hostname: alicia_tpm.hcphacking.xyz
        volumes:
          - tpm_alicia:/tpm_alicia
          - tpmsocket_alicia:/tpmsocket_alicia
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/alicia.json

    auth_certificate:
        extends: common_nontpm
        hostname: certificate.auth.hcphacking.xyz
        volumes:
          - tpmsocket_auth_certificate:/tpmsocket_auth_certificate
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/auth_certificate.json

    auth_certificate_tpm:
        extends: common_tpm
        hostname: auth_certificate_tpm.hcphacking.xyz
        volumes:
          - tpm_auth_certificate:/tpm_auth_certificate
          - tpmsocket_auth_certificate:/tpmsocket_auth_certificate
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/auth_certificate.json

    auth_kerberos:
        extends: common_nontpm
        hostname: kerberos.auth.hcphacking.xyz
        volumes:
          - tpmsocket_auth_kerberos:/tpmsocket_auth_kerberos
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/auth_kerberos.json

    auth_kerberos_tpm:
        extends: common_tpm
        hostname: auth_kerberos_tpm.hcphacking.xyz
        volumes:
          - tpm_auth_kerberos:/tpm_auth_kerberos
          - tpmsocket_auth_kerberos:/tpmsocket_auth_kerberos
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/auth_kerberos.json

#### X1 hosts

    x1_kdc:
        extends: common_nontpm
        hostname: kdc.x1.hcphacking.xyz
        volumes:
          - x1_kdc:/x1_kdc
          - x1_backdoor:/x1_backdoor
          - ./_testcreds/caprivate:/caprivate:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_kdc.json

    x1_sshd:
        extends: common_nontpm
        hostname: sshd.x1.hcphacking.xyz
        volumes:
          - x1_backdoor:/x1_backdoor
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_sshd.json

    x1_client:
        extends: common_nontpm
        hostname: client.x1.hcphacking.xyz
        volumes:
          - x1_backdoor:/x1_backdoor
          - ./_testcreds/caprivate:/caprivate:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_client.json
