COPY heimdal-install.tar.gz nginx-heimdal-install.tar.gz /
RUN cd / && tar zxf heimdal-install.tar.gz && rm heimdal-install.tar.gz
RUN cd / && tar zxf nginx-heimdal-install.tar.gz && rm nginx-heimdal-install.tar.gz
RUN echo "/install-heimdal/lib" >> /etc/ld.so.conf.d/heimdal.conf
RUN ldconfig
