# vim: set expandtab shiftwidth=4 softtabstop=4 :
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    enrolldb:
    attestdb:
    kdc_primary:
    kdc_secondary:
    tpm_attestclient:
    tpmsocket_attestclient:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_kdc_keytab:
    tpmsocket_kdc_keytab:
    tpm_ssherver1:
    tpmsocket_ssherver1:
    tpm_ssherver2:
    tpmsocket_ssherver2:
    tpm_workstation1:
    tpmsocket_workstation1:
    tpm_bigbrother:
    tpm_www:
    tpmsocket_www:

networks:
    hcpnetwork:
        # internal: true

services:
    common:
        image: hcp_caboodle:trixie
        init: true
        volumes:
          - ${TOP}/hcp:/hcp:ro
          - ${TOP}/safeboot:/install-safeboot
          - ./usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}
          - PYTHONPATH=/hcp/python
        healthcheck:
            test: /hcp/python/HcpToolHealthcheck.py
            timeout: 10s
            interval: 20s

    common_tpm:
        extends: common
        network_mode: "none"
        environment:
          - HCP_CONFIG_SCOPE=.tpm

    common_nontpm:
        extends: common
        networks:
          - hcpnetwork
        volumes:
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollhealthclient:/enrollhealthclient:ro

    policy:
        extends: common_nontpm
        hostname: policy.hcphacking.xyz
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/policy.json

    emgmt:
        extends: common_nontpm
        hostname: emgmt.hcphacking.xyz
        volumes:
          - enrolldb:/enrolldb:rw
          - ./_testcreds/enrollsigner:/enrollsigner:ro
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollserver:/enrollserver:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/emgmt.json

    erepl:
        extends: common_nontpm
        hostname: erepl.hcphacking.xyz
        volumes:
          - enrolldb:/enrolldb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/erepl.json

    arepl:
        extends: common_nontpm
        hostname: arepl.hcphacking.xyz
        volumes:
          - attestdb:/attestdb:rw
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/arepl.json
        healthcheck:
            test: test -f /attestdb/initialized && ! test -f /attestdb/hcp/transient-failure

    ahcp:
        extends: common_nontpm
        hostname: ahcp.hcphacking.xyz
        volumes:
          - attestdb:/attestdb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ahcp.json

    orchestrator:
        extends: common_nontpm
        hostname: orchestrator.hcphacking.xyz
        volumes:
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - tpm_attestclient:/tpm_attestclient
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpm_kdc_keytab:/tpm_keytab.kdc
          - tpm_ssherver1:/tpm_ssherver1
          - tpm_ssherver2:/tpm_ssherver2
          - tpm_workstation1:/tpm_workstation1
          - tpm_bigbrother:/tpm_bigbrother
          - tpm_www:/tpm_www
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/orchestrator.json

    attestclient:
        extends: common_nontpm
        hostname: attestclient.hcphacking.xyz
        volumes:
          - tpmsocket_attestclient:/tpmsocket_attestclient
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/attestclient.json

    attestclient_tpm:
        extends: common_tpm
        hostname: attestclient_tpm.hcphacking.xyz
        volumes:
          - tpm_attestclient:/tpm_attestclient
          - tpmsocket_attestclient:/tpmsocket_attestclient
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/attestclient.json

    kdc_primary:
        extends: common_nontpm
        hostname: primary.kdc.hcphacking.xyz
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_primary_tpm:
        extends: common_tpm
        hostname: kdc_primary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_secondary:
        extends: common_nontpm
        hostname: secondary.kdc.hcphacking.xyz
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_secondary_tpm:
        extends: common_tpm
        hostname: kdc_secondary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_keytab:
        extends: common_nontpm
        hostname: keytab.kdc.hcphacking.xyz
        volumes:
          - tpmsocket_kdc_keytab:/tpmsocket_keytab.kdc
          - ./_testcreds/enrollclient:/enrollclient:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_keytab.json

    kdc_keytab_tpm:
        extends: common_tpm
        hostname: kdc_keytab_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_keytab:/tpm_keytab.kdc
          - tpmsocket_kdc_keytab:/tpmsocket_keytab.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_keytab.json

    ssherver1:
        extends: common_nontpm
        hostname: ssherver1.hcphacking.xyz
        volumes:
          - tpmsocket_ssherver1:/tpmsocket_ssherver1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver1.json

    ssherver1_tpm:
        extends: common_tpm
        hostname: ssherver1_tpm.hcphacking.xyz
        volumes:
          - tpm_ssherver1:/tpm_ssherver1
          - tpmsocket_ssherver1:/tpmsocket_ssherver1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver1.json

    ssherver2:
        extends: common_nontpm
        hostname: ssherver2.hcphacking.xyz
        volumes:
          - tpmsocket_ssherver2:/tpmsocket_ssherver2
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver2.json

    ssherver2_tpm:
        extends: common_tpm
        hostname: ssherver2_tpm.hcphacking.xyz
        volumes:
          - tpm_ssherver2:/tpm_ssherver2
          - tpmsocket_ssherver2:/tpmsocket_ssherver2
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver2.json

    workstation1:
        extends: common_nontpm
        hostname: workstation1.hcphacking.xyz
        volumes:
          - tpmsocket_workstation1:/tpmsocket_workstation1
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/workstation1.json

    workstation1_tpm:
        extends: common_tpm
        hostname: workstation1_tpm.hcphacking.xyz
        volumes:
          - tpm_workstation1:/tpm_workstation1
          - tpmsocket_workstation1:/tpmsocket_workstation1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/workstation1.json

    bigbrother:
        extends: common_nontpm
        hostname: bigbrother.hcphacking.xyz
        volumes:
          - tpm_bigbrother:/tpm_bigbrother
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/bigbrother.json

    www:
        extends: common_nontpm
        hostname: www.hcphacking.xyz
        networks:
          hcpnetwork:
            aliases:
              - www2.hcphacking.xyz
        volumes:
          - tpmsocket_www:/tpmsocket_www
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/www.json

    www_tpm:
        extends: common_tpm
        hostname: www_tpm.hcphacking.xyz
        volumes:
          - tpm_www:/tpm_www
          - tpmsocket_www:/tpmsocket_www
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/www.json
