# vim: set expandtab shiftwidth=4 softtabstop=4 :
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    enrolldb:
    attestdb:
    kdc_primary:
    kdc_secondary:
    ssherver:
    tpm_aclient:
    tpmsocket_aclient:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_ssherver:
    tpmsocket_ssherver:
    tpm_workstation1:
    tpmsocket_workstation1:
    tpm_bigbrother:
    tpm_www:
    tpmsocket_www:

networks:
    hcpnetwork:
        # internal: true
    emgmt_private:
        internal: true
    kdc_primary_private:
        internal: true
    kdc_secondary_private:
        internal: true

services:
    common:
        image: hcp_caboodle:trixie
        init: true
        volumes:
          - ${TOP}/hcp:/hcp:ro
          - ${TOP}/safeboot:/install-safeboot
          - ./usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}
          - PYTHONPATH=/hcp/python
        healthcheck:
            test: /hcp/python/HcpToolHealthcheck.py
            timeout: 10s
            interval: 20s

    common_tpm:
        extends: common
        network_mode: "none"
        environment:
          - HCP_CONFIG_SCOPE=.tpm

    policy:
        extends: common
        hostname: policy.hcphacking.xyz
        networks:
          - hcpnetwork
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/policy.json

    emgmt:
        extends: common
        hostname: emgmt.hcphacking.xyz
        networks:
          - hcpnetwork
          - emgmt_private
        volumes:
          - enrolldb:/enrolldb:rw
          - ./_testcreds/enrollsigner:/enrollsigner:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollserver:/enrollserver:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/emgmt.json

    erepl:
        extends: common
        hostname: erepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - enrolldb:/enrolldb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/erepl.json

    arepl:
        extends: common
        hostname: arepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:rw
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/arepl.json
        healthcheck:
            test: test -f /attestdb/initialized && ! test -f /attestdb/hcp/transient-failure

    ahcp:
        extends: common
        hostname: ahcp.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ahcp.json

    orchestrator:
        extends: common
        hostname: orchestrator.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - tpm_aclient:/tpm_aclient
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpm_ssherver:/tpm_ssherver
          - tpm_workstation1:/tpm_workstation1
          - tpm_bigbrother:/tpm_bigbrother
          - tpm_www:/tpm_www
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/orchestrator.json

    aclient:
        extends: common
        hostname: aclient.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_aclient:/tpmsocket_aclient
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/aclient.json

    aclient_tpm:
        extends: common_tpm
        hostname: aclient_tpm.hcphacking.xyz
        volumes:
          - tpm_aclient:/tpm_aclient
          - tpmsocket_aclient:/tpmsocket_aclient
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/aclient.json

    kdc_primary:
        extends: common
        hostname: primary.kdc.hcphacking.xyz
        networks:
          - hcpnetwork
          - kdc_primary_private
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_primary_tpm:
        extends: common_tpm
        hostname: kdc_primary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_secondary:
        extends: common
        hostname: secondary.kdc.hcphacking.xyz
        networks:
          - hcpnetwork
          - kdc_secondary_private
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_secondary_tpm:
        extends: common_tpm
        hostname: kdc_secondary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    ssherver:
        extends: common
        hostname: ssherver.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - ssherver:/ssherver
          - tpmsocket_ssherver:/tpmsocket_ssherver
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver.json

    ssherver_tpm:
        extends: common_tpm
        hostname: ssherver_tpm.hcphacking.xyz
        volumes:
          - tpm_ssherver:/tpm_ssherver
          - tpmsocket_ssherver:/tpmsocket_ssherver
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/ssherver.json

    workstation1:
        extends: common
        hostname: workstation1.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_workstation1:/tpmsocket_workstation1
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/workstation1.json

    workstation1_tpm:
        extends: common_tpm
        hostname: workstation1_tpm.hcphacking.xyz
        volumes:
          - tpm_workstation1:/tpm_workstation1
          - tpmsocket_workstation1:/tpmsocket_workstation1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/workstation1.json

    bigbrother:
        extends: common
        hostname: bigbrother.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpm_bigbrother:/tpm_bigbrother
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/bigbrother.json

    www:
        extends: common
        hostname: www.hcphacking.xyz
        networks:
          hcpnetwork:
            aliases:
              - www2.hcphacking.xyz
        volumes:
          - tpmsocket_www:/tpmsocket_www
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/www.json

    www_tpm:
        extends: common_tpm
        hostname: www_tpm.hcphacking.xyz
        volumes:
          - tpm_www:/tpm_www
          - tpmsocket_www:/tpmsocket_www
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/www.json
