# vim: set expandtab shiftwidth=4 softtabstop=4 :
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    example:
    tpm_host1:
    tpmsocket_host1:
    kdc_primary:
    kdc_secondary:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_kdc_keytab:
    tpmsocket_kdc_keytab:
    x1_kdc:
    x1_backdoor:

networks:
    hcpnetwork:
        # internal: true

services:
    common:
        image: hcp_caboodle:trixie
        init: true
        volumes:
          - ${TOP}/hcp:/hcp:ro
          - ./usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}
          - PYTHONPATH=/hcp/python
        healthcheck:
            test: /hcp/python/HcpToolHealthcheck.py
            timeout: 10s
            interval: 20s

    common_tpm:
        extends: common
        network_mode: "none"
        environment:
          - HCP_CONFIG_SCOPE=.tpm

    common_nontpm:
        extends: common
        networks:
          - hcpnetwork
        volumes:
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollhealthclient:/enrollhealthclient:ro

    orchestrator:
        extends: common_nontpm
        hostname: orchestrator.hcphacking.xyz
        volumes:
          - ./_testcreds/enrollclient:/enrollclient:ro
          - tpm_host1:/tpm_host1
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpm_kdc_keytab:/tpm_keytab.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/orchestrator.json

    host1:
        extends: common_nontpm
        hostname: host1.hcphacking.xyz
        volumes:
          - tpmsocket_host1:/tpmsocket_host1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/host1.json

    host1_tpm:
        extends: common_tpm
        hostname: host1_tpm.hcphacking.xyz
        volumes:
          - tpm_host1:/tpm_host1
          - tpmsocket_host1:/tpmsocket_host1
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/host1.json

    enrollsvc:
        extends: common_nontpm
        hostname: enrollsvc.hcphacking.xyz
        volumes:
          - example:/example
          - ./_testcreds/enrollserver:/enrollserver:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/enrollsvc.json

    attestsvc:
        extends: common_nontpm
        hostname: attestsvc.hcphacking.xyz
        volumes:
          - example:/example
          - ./_testcreds/attestserver:/attestserver:ro
          - ./_testcreds/attestnoncer:/attestnoncer:ro
          - ./_testcreds/enrollsigner:/enrollsigner:ro
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/attestsvc.json

    kdc_primary:
        extends: common_nontpm
        hostname: primary.kdc.hcphacking.xyz
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_primary_tpm:
        extends: common_tpm
        hostname: kdc_primary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_primary:/tpm_primary.kdc
          - tpmsocket_kdc_primary:/tpmsocket_primary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_primary.json

    kdc_secondary:
        extends: common_nontpm
        hostname: secondary.kdc.hcphacking.xyz
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_secondary_tpm:
        extends: common_tpm
        hostname: kdc_secondary_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_secondary:/tpm_secondary.kdc
          - tpmsocket_kdc_secondary:/tpmsocket_secondary.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_secondary.json

    kdc_keytab:
        extends: common_nontpm
        hostname: keytab.kdc.hcphacking.xyz
        volumes:
          - tpmsocket_kdc_keytab:/tpmsocket_keytab.kdc
          - ./_testcreds/enrollclient:/enrollclient:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_keytab.json

    kdc_keytab_tpm:
        extends: common_tpm
        hostname: kdc_keytab_tpm.hcphacking.xyz
        volumes:
          - tpm_kdc_keytab:/tpm_keytab.kdc
          - tpmsocket_kdc_keytab:/tpmsocket_keytab.kdc
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/kdc_keytab.json

#### X1 hosts

    x1_kdc:
        extends: common_nontpm
        hostname: kdc.x1.hcphacking.xyz
        volumes:
          - x1_kdc:/x1_kdc
          - x1_backdoor:/x1_backdoor
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_kdc.json

    x1_sshd:
        extends: common_nontpm
        hostname: sshd.x1.hcphacking.xyz
        volumes:
          - x1_backdoor:/x1_backdoor
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_sshd.json

    x1_client:
        extends: common_nontpm
        hostname: client.x1.hcphacking.xyz
        volumes:
          - x1_backdoor:/x1_backdoor
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/hosts/x1_client.json
