# vim: set expandtab shiftwidth=4 softtabstop=4 :
# Using this version string helps with some older docker-compose versions that
# we regularly encounter. It also ensures the 'extend' feature works.
version: "2.4"

volumes:
    enrolldb:
    attestdb:
    kdc_primary:
    kdc_secondary:
    sherver:
    tpm_aclient:
    tpmsocket_aclient:
    tpm_kdc_primary:
    tpmsocket_kdc_primary:
    tpm_kdc_secondary:
    tpmsocket_kdc_secondary:
    tpm_sherver:
    tpmsocket_sherver:
    tpm_workstation1:
    tpmsocket_workstation1:
    tpm_bigbrother:
    tpm_www:
    tpmsocket_www:

networks:
    hcpnetwork:
        # internal: true
    emgmt_private:
        internal: true
    kdc_primary_private:
        internal: true
    kdc_secondary_private:
        internal: true

services:
    common:
        image: hcp_caboodle:trixie
        init: true
        volumes:
          - ./usecase:/usecase:ro
        environment:
          - HCP_LAUNCHER_TGTS=${HCP_LAUNCHER_TGTS:-}
          - HCP_NOTRACEFILE=1
          - VERBOSE=${VERBOSE:-0}
        healthcheck:
            timeout: 10s
            interval: 20s

    emgmt:
        extends: common
        hostname: emgmt.hcphacking.xyz
        networks:
          - hcpnetwork
          - emgmt_private
        volumes:
          - enrolldb:/enrolldb:rw
          - ./_testcreds/enrollsigner:/enrollsigner:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertissuer:/enrollcertissuer:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollserver:/enrollserver:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    emgmt_pol:
        extends: common
        hostname: policy.emgmt.hcphacking.xyz
        networks:
          - emgmt_private
        environment:
          - HCP_CONFIG_FILE=/usecase/emgmt_pol.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    erepl:
        extends: common
        hostname: erepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - enrolldb:/enrolldb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/erepl.json
        healthcheck:
            test: /hcp/enrollsvc/repl_healthcheck.sh

    arepl:
        extends: common
        hostname: arepl.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:rw
        environment:
          - HCP_CONFIG_FILE=/usecase/arepl.json
        healthcheck:
            test: test -f /attestdb/initialized && ! test -f /attestdb/hcp/transient-failure

    ahcp:
        extends: common
        hostname: ahcp.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - attestdb:/attestdb:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/ahcp.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    orchestrator:
        extends: common
        hostname: orchestrator.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - tpm_aclient:/tpm_aclient
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpm_sherver:/tpm_sherver
          - tpm_workstation1:/tpm_workstation1
          - tpm_bigbrother:/tpm_bigbrother
          - tpm_www:/tpm_www
        environment:
          - HCP_CONFIG_FILE=/usecase/orchestrator.json

    aclient:
        extends: common
        hostname: aclient.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_aclient:/tpm_socket_aclient
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient.json

    aclient_tpm:
        extends: common
        hostname: aclient_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_aclient:/tpm_aclient
          - tpmsocket_aclient:/tpm_socket_aclient
        environment:
          - HCP_CONFIG_FILE=/usecase/aclient_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck

    kdc_primary:
        extends: common
        hostname: primary.kdc.hcphacking.xyz
        networks:
          - hcpnetwork
          - kdc_primary_private
        volumes:
          - kdc_primary:/kdc_primary
          - tpmsocket_kdc_primary:/tpmsocket_kdc_primary
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    kdc_primary_tpm:
        extends: common
        hostname: kdc_primary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_primary:/tpm_kdc_primary
          - tpmsocket_kdc_primary:/tpm_socket_kdc_primary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck

    kdc_primary_pol:
        extends: common
        hostname: policy.primary.kdc.hcphacking.xyz
        networks:
          - kdc_primary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_primary_pol.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    kdc_secondary:
        extends: common
        hostname: secondary.kdc.hcphacking.xyz
        networks:
          - hcpnetwork
          - kdc_secondary_private
        volumes:
          - kdc_secondary:/kdc_secondary
          - tpmsocket_kdc_secondary:/tpmsocket_kdc_secondary
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    kdc_secondary_tpm:
        extends: common
        hostname: kdc_secondary_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_kdc_secondary:/tpm_kdc_secondary
          - tpmsocket_kdc_secondary:/tpm_socket_kdc_secondary
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck

    kdc_secondary_pol:
        extends: common
        hostname: policy.secondary.kdc.hcphacking.xyz
        networks:
          - kdc_secondary_private
        environment:
          - HCP_CONFIG_FILE=/usecase/kdc_secondary_pol.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck

    sherver:
        extends: common
        hostname: sherver.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - sherver:/sherver
          - tpmsocket_sherver:/tpmsocket_sherver
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver.json
        healthcheck:
            test: /hcp/sshd.py --healthcheck

    sherver_tpm:
        extends: common
        hostname: sherver_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_sherver:/tpm_sherver
          - tpmsocket_sherver:/tpmsocket_sherver
        environment:
          - HCP_CONFIG_FILE=/usecase/sherver_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck

    workstation1:
        extends: common
        hostname: workstation1.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpmsocket_workstation1:/tpmsocket_workstation1
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1.json
        healthcheck:
            test: /hcp/attested.py

    workstation1_tpm:
        extends: common
        hostname: workstation1_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_workstation1:/tpm_workstation1
          - tpmsocket_workstation1:/tpmsocket_workstation1
        environment:
          - HCP_CONFIG_FILE=/usecase/workstation1_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck

    bigbrother:
        extends: common
        hostname: bigbrother.hcphacking.xyz
        networks:
          - hcpnetwork
        volumes:
          - tpm_bigbrother:/tpm_bigbrother
          - ./_testcreds/enrollverifier:/enrollverifier:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/bigbrother.json
        healthcheck:
            test: /hcp/attested.py

    www:
        extends: common
        hostname: www.hcphacking.xyz
        networks:
          hcpnetwork:
            aliases:
              - www2.hcphacking.xyz
        volumes:
          - tpmsocket_www:/tpmsocket_www
          - ./_testcreds/enrollverifier:/enrollverifier:ro
          - ./_testcreds/enrollcertchecker:/enrollcertchecker:ro
          - ./_testcreds/enrollclient:/enrollclient:ro
        environment:
          - HCP_CONFIG_FILE=/usecase/www.json
        healthcheck:
            test: /hcp/webapi.py --healthcheck -C webapi && /hcp/webapi.py --healthcheck -C webapi2

    www_tpm:
        extends: common
        hostname: www_tpm.hcphacking.xyz
        network_mode: "none"
        volumes:
          - tpm_www:/tpm_www
          - tpmsocket_www:/tpmsocket_www
        environment:
          - HCP_CONFIG_FILE=/usecase/www_tpm.json
        healthcheck:
            test: /hcp/swtpm.py --healthcheck
