COPY mit-install.tar.gz kstart-install.tar.gz nginx-mit-install.tar.gz /
RUN cd / && tar zxf mit-install.tar.gz && rm mit-install.tar.gz
RUN cd / && tar zxf kstart-install.tar.gz && rm kstart-install.tar.gz
RUN cd / && tar zxf nginx-mit-install.tar.gz && rm nginx-mit-install.tar.gz
RUN echo "/install-mit/lib" >> /etc/ld.so.conf.d/mit.conf
RUN ldconfig
