#!/usr/bin/python3

import os
import sys
import subprocess
import argparse
import time
import shutil

import hcp.common as h

myinstance = h.hcp_config_extract(".vars.id", must_exist = True)
myexports = h.hcp_config_extract(".vars.nfsd_exports", must_exist = True)
if not isinstance(myexports, list):
	raise Exception('nfsd_exports must be list type')

parser = argparse.ArgumentParser()
parser.add_argument("--healthcheck", action = "store_true",
		help = "check that NFS service is running ok")
args = parser.parse_args()

if args.healthcheck:
	h.hlog(1, 'Not working yet')
	sys.exit(1)

print("Creating /etc/exports")
with open('/etc/exports', 'w') as fp:
	fp.write('''#
# Auto-generated by nfsd.py
''')
	for i in myexports:
		fp.write(f"{i}\n")

print("Running 'exportfs -ra'")
subprocess.run(['exportfs', '-ra'])

torestart = ['rpc-svcgssd', 'rpc-gssd', 'rpcbind']
print(f"Restarting {' '.join(torestart)}")
for s in torestart:
	subprocess.run(['systemctl', 'restart', s])
